In [1]:
import torch

In [8]:
x = torch.empty(5,3)
print(torch.rand(1,3, dtype=torch.float))
print(torch.zeros(1,2))
print(torch.tensor([[3,5],
                    [4,8]]))

tensor([[0.0724, 0.0407, 0.5673]])
tensor([[0., 0.]])
tensor([[3, 5],
        [4, 8]])


In [12]:
x = x.new_ones(5,3)
print(x.size())

y = torch.randn_like(x)

torch.Size([5, 3])


In [15]:
print(x+y)
y.add_(x)
z = torch.empty(5, 3)
torch.add(x,y,out=z)
print(z[:,2])

tensor([[2.8317, 2.1980, 0.8118],
        [1.3976, 3.4908, 3.4041],
        [1.5731, 4.3204, 0.2056],
        [0.7986, 1.8143, 2.9853],
        [1.4761, 1.3524, 3.4218]])
tensor([1.8118, 4.4041, 1.2056, 3.9853, 4.4218])


In [17]:
print(x.view(-1,5)) #resize

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [19]:
print(torch.randn(1).item())

0.17360273003578186
