In [1]:
import torch

In [2]:
x = torch.empty(5,3)
print(torch.rand(1,3, dtype=torch.float))
print(torch.zeros(1,2))
print(torch.tensor([[3,5],
                    [4,8]]))

tensor([[0.8305, 0.7784, 0.1548]])
tensor([[0., 0.]])
tensor([[3, 5],
        [4, 8]])


In [3]:
x = x.new_ones(5,3)
print(x.size())

y = torch.randn_like(x)

torch.Size([5, 3])


In [4]:
print(x+y)
y.add_(x)
z = torch.empty(5, 3)
torch.add(x,y,out=z)
print(z[:,2])

tensor([[ 0.9785,  0.7344, -0.3164],
        [-0.7010,  1.8694,  1.7804],
        [ 0.6680,  0.9819, -0.5236],
        [ 1.8515,  2.4365,  2.2649],
        [ 2.5291,  0.2831,  0.9861]])
tensor([0.6836, 2.7804, 0.4764, 3.2649, 1.9861])


In [5]:
print(x.view(-1,5)) #resize

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [6]:
print(torch.randn(1).item())

-0.27621254324913025


In [13]:
print(torch.randn_like(x, dtype=torch.double))#int or long not valid

tensor([[-1.2669,  0.7759, -1.4680],
        [ 0.5722,  0.4123, -0.4843],
        [-0.1646, -0.8530,  0.0073],
        [-1.1658,  0.8747,  1.4388],
        [ 0.6895,  0.5324,  1.0518]], dtype=torch.float64)


In [16]:
import numpy as np
a = np.zeros((3, 3), dtype=np.int32)
print(torch.from_numpy(a))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
